--- #YAML:1.0
name:                Wx
version:             0.81
abstract:            interface to the wxWidgets cross-platform GUI toolkit
license:             perl
author:              
    - Mattia Barbon <mbarbon@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Alien::wxWidgets:              0.25
    Data::Dumper:                  0
    ExtUtils::MakeMaker:           6.17
    File::Spec::Functions:         0.82
    Test::Harness:                 2.26
    Test::More:                    0.45
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
