--- #YAML:1.0
name:               Wx
version:            0.9906
abstract:           interface to the wxWidgets cross-platform GUI toolkit
author:
    - Mattia Barbon <mbarbon@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    Alien::wxWidgets:  0.25
build_requires:
    Alien::wxWidgets:     0.25
    ExtUtils::MakeMaker:  6.48
    ExtUtils::ParseXS:    3.15
    ExtUtils::XSpp:       0.1602
    File::Spec::Functions:  0.82
    if:                   0.03
    Test::Harness:        2.26
    Test::More:           0.45
requires:
    Alien::wxWidgets:  0.25
resources:
    bugtracker:   http://rt.cpan.org/NoAuth/Bugs.html?Dist=Wx
    homepage:     http://wxperl.eu/
    license:      http://dev.perl.org/licenses/
    MailingList:  http://lists.perl.org/list/wxperl-users.html
    repository:   https://wxperl.svn.sourceforge.net/svnroot/wxperl/wxPerl
no_index:
    directory:
        - samples
        - script
    package:
        - MY
        - Parse::Yapp::Driver
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
dynamic_config:     1
